### ISSUE TITLE
Question about 0.2 release

### ISSUE THREAD

**Issue by AbrilRBS** [jart/jtckdint#6]
Hi!

As part of our review for inclusion of the library in Conan Center https://github.com/conan-io/conan-center-index/pull/26015, I noticed that [the 0.2 tag](https://github.com/jart/jtckdint/releases/tag/0.2) is from 2023, but [the most recent commit](https://github.com/jart/jtckdint/commit/9cf58eea25d9148d0b5553cf9045ca8d877b9789) seems to imply that 0.2 is expected to be released now.
Is then a new tag expected soon, or should I ignore the commit message? Thanks :)

**Comment by jart** [comment]
Thanks for noticing that. Wow that was confusing. I've fixed the git history and cut a 1.0 release. Enjoy!
